### ISSUE TITLE
Splash screen for iPhone6 and iPhone6+

### ISSUE THREAD

**Issue by kfateem** [busterc/cordova-resource-generators#1]
The following resolutions are missing-
## Icon:

icon-60@3x.png
## Splash:

Default-667h.png
Default-736h.png
Default-Landscape-736h.png

**Comment by bobalazek** [comment]
+1

**Comment by OlegPasko** [comment]
+1 :)

**Comment by wwallace** [comment]
+1
Here is the pull request: https://github.com/busterc/cordova-resource-generators/pull/2

**Comment by busterc** [comment]
Sorry for being so tardy on this one. The iPhone 6 (Plus) splash screen conversions were added with @wwallace PR; thanks!

The icon was added on 83bd4d8ff6dc9f3e199fc619927d6d623ca484b6
